require 'watir'
require 'watir-webdriver'
require 'selenium-webdriver'

require 'watir_formhandler/watir'
require 'watir_formhandler/element'
require 'watir_formhandler/option_group'
require 'watir_formhandler/container'
require 'watir_formhandler/browser'
require 'watir_formhandler/check_box'
require 'watir_formhandler/select'
