require 'watir'
require 'watir-webdriver'
require 'selenium-webdriver'

require 'watir-formhandler/watir'
require 'watir-formhandler/element'
require 'watir-formhandler/option_group'
require 'watir-formhandler/container'
require 'watir-formhandler/check_box'
require 'watir-formhandler/select'
require 'watir-formhandler/radio'
require 'watir-formhandler/text_field'
require 'watir-formhandler/text_area'
require 'watir-formhandler/file_field'
